
name: get_installation
channels:
- defaults
- conda-forge
dependencies:
  - pip:
    - numpy
    - streamlit
    - pythainlp
    - icevision
    - setuptools==59.5.0
    - mmcv
    - easyocr
    - editdistance


