
name: get_installation
channels:
- defaults
- conda-forge
dependencies:
  - pip:
    - streamlit
    - numpy
    - Pillow
    - pythainlp==3.0.8
    - icevision
    - setuptools==59.5.0
    - mmcv
    - easyocr==1.5.0
    - editdistance


