
name: get_installation
channels:
- defaults
- conda-forge
dependencies:
  - pip:
    - streamlit
    - numpy==1.18.3
    - Pillow
    - pythainlp
    - icevision
    - setuptools==59.5.0
    - mmcv
    - easyocr==1.5.0
    - editdistance


